### ISSUE TITLE
I followed the demo, but the word didn't show

### ISSUE THREAD

**Issue by sammychiang** [chanind/hanzi-writer-miniprogram#3]
here is the minicode https://developers.weixin.qq.com/s/0ORUOKmr7F94

and I didn't add https://cdn.jsdelivr.net to the list of the approved domain, as i make the IDE don't check it, is this matter?

![image](https://user-images.githubusercontent.com/6251979/60943603-0c74c580-a319-11e9-82a9-ce3fbad1bba5.png)

**Comment by sammychiang** [comment]
resolved as i delete the option " charDataLoader: (char) => { /* char data loading logic here */ } " in demo code

**Comment by chanind** [comment]
ah sorry about that! I'll update the docs to remove that line. I can see how that would be confusing.
