### ISSUE TITLE
Abnormal display of real machine

### ISSUE THREAD

**Issue by zzzzhe** [chanind/hanzi-writer-miniprogram#4]
In the simulator of the wechat miniprogram development environment, the display of canvas Chinese characters is correct.  however, on a real machine, preview, canvas's strokes looks like reversed, scale problem?   iPhone6+  In latest version of WeChat.

**Comment by sammychiang** [comment]
same issue. no problem on android and IDE, but only show a stroke on iphone6 Plus. No error logged.
On IDE or android

**Comment by chanind** [comment]
This looks like it's the same issue as in the bottom of https://github.com/chanind/hanzi-writer/issues/121. I still haven't been able to get a hold of an iPhone to debug further. If you're able to figure out what the issue is please submit a PR!

**Comment by chanind** [comment]
this should be fixed in 1.0.4 now thanks to @kevin82008! Let me know if there's still issues on iOS.

**Comment by sammychiang** [comment]
great, i have tested,  this has been resolved on iPhone.
